name: Release Drafter

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install && pnpm build
    - name: Rename file
      run: mv ./dist/adhoc-translate.user.js ./dist/adhoc-translate.${{ github.ref_name }}.user.js

    - name: Update Release Draft
      id: release-drafter
      uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        name: ${{ github.ref_name }}
        tag: ${{ github.ref_name }}
        publish: true
        latest: true
        version: ${{ github.ref_type == 'tag' && github.ref_name || null }}
        prerelease: ${{ github.ref_name == 'main' }}

    - uses: AButler/upload-release-assets@v3.0
      with:
        release-id: ${{ steps.release-drafter.outputs.id }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: ./dist/adhoc-translate.${{ github.ref_name }}.user.js
