name: Release Drafter

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Release Please Action
      id: release-please
      uses: googleapis/release-please-action@v4
      with:
        release-type: node
        target-branch: ${{ github.ref_name }}

    # - name: Update Release Draft
    #   id: release-drafter
    #   uses: release-drafter/release-drafter@v6
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     CHANGELOG_REF: ${{ github.ref_name == 'main' && 'alpha' || github.ref_name }}
    #   with:
    #     tag: ${{ github.ref_name == 'main' && 'alpha' || github.ref_name }}
    #     commitish: ${{ github.ref }}
    #     version: ${{ github.ref_type == 'tag' && github.ref_name || null }}
    #     publish: true
    #     prerelease: ${{ github.ref_name == 'main' }}
    #     prerelease-identifier: 'alpha'

    - name: Install dependencies
      run: pnpm install && pnpm build
      if: ${{ steps.release-please.outputs.release_created }}
      env:
        RESOLVED_VERSION: >-
          ${{ steps.release-please.outputs.major }}.${{ steps.release-please.outputs.minor }}.${{ steps.release-please.outputs.patch }}

    - name: Upload file
      uses: AButler/upload-release-assets@v3.0
      if: ${{ steps.release-please.outputs.release_created }}
      with:
        release-tag: ${{ steps.release-please.outputs.tag_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: ./dist/adhoc-translate.user.js
